FROM alpine:latest

RUN apk update && apk add nginx && rm -rf /var/cache/apk/*

RUN mkdir -p /var/www/localhost/htdocs && mkdir -p /run/nginx

COPY index.html /var/www/localhost/htdocs/index.html

COPY nginx.conf /etc/nginx/http.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
